### ISSUE TITLE
Nonce for strobe session

### ISSUE THREAD

**Issue by GabrieleGalli** [rozbb/strobe-rs#5]
Hi, for my application I am using a strobe session between a client and a server to encrypt messages with a symmetric key.
I was wondering if it would be possible to access/modify the nonce as for an aead contex in order to invalidate the symmetric key after a certain number of exchanged messages.
Thanks in advance.

**Comment by rozbb** [comment]
Hi again! I'm not sure I understand. Do you have a nonce somewhere that you're incrementing that you want to delete? STROBE is a stateful protocol, so it doesn't explicitly uses nonces.

That said, there is a use for nonces for semantic security. The code I wrote [previously](https://github.com/rozbb/rust-hpke/issues/33#issuecomment-1317735314) is only secure if you use the key once. If you use the key twice, and send the same messages, then the ciphertext will be the same. This is bad because anyone on the network can see that the same messages were sent. A random nonce at the beginning of the session will eliminate this issue.

To use a a nonce with STROBE, you can use the `Strobe::ad` or `Strobe::recv_clr/Strobe::send_clr` methods, as explained in more detail [here](https://strobe.sourceforge.io/examples/aead/) (in fact, I should probably put that in the documentation). Concretely, building on the code I previously wrote:
```rust
let mut csprng = rand::thread_rng();
// Make a new STROBE session and key it with some shared secret
ctx = Strobe::new(b"mysession", SecParam::B128);
ctx.key(&shared_secret, false);
// Make a random nonce and put it into the STROBE session
let nonce = [0u8; 24];
csprng.fill_bytes(&mut nonce);
ctx.ad(nonce, false);
// Encrypt a message
let mut msg = b"hello world";
ctx.send_enc(&mut msg, false);

// msg is now encrypted. S sends msg and nonce to someone else.

// Recipient:
ctx = Strobe::new(b"mysession", SecParam::B128);
// Read in the nonce
ctx.ad(nonce, false);
// Key the session
ctx.key(&shared_secret, false);
// Decrypt the message
ctx.recv_enc(&mut msg, false);
println!("Got {}", String::from_utf8_lossy(msg));
```
Note that, after the first nonce is sent, you don't need any more nonces. This is because STROBE is stateful.
